#!/bin/bash

echo "# Autogenerated cmake file. Do not edit." > $CMAKE_BINARY_DIR/config.cmake
echo "// Autogenerated header file. Do not edit." > config.h
echo "#ifndef __CONFIG_H__" >> config.h
echo "#define __CONFIG_H__" >> config.h
while read -r line; do
  if [[ `expr "$line" : "CONFIG_"` -ne 7 ]]; then
    continue;
  fi;
  name=`echo $line | cut -d"=" -f1`
  value=`echo $line | cut -d"=" -f2`
  echo "#define $name $value" >> config.h
  echo "set($name $value)" >> $CMAKE_BINARY_DIR/config.cmake
done < $1
echo "#endif" >> config.h
