function(phabos_add_srcs)
  foreach(arg ${ARGV})
    set_property(GLOBAL APPEND PROPERTY _PHABOS_SRCS ${CMAKE_CURRENT_SOURCE_DIR}/${arg})
  endforeach()
endfunction()

function(phabos_add_includes)
  foreach(arg ${ARGV})
    set_property(GLOBAL APPEND PROPERTY _PHABOS_INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}/${arg})
  endforeach()
endfunction()

function(phabos_cond_compile MODULE_NAME SRCS)
  message("Module: ${MODULE_NAME}")
  if(${MODULE_NAME})
    foreach(f ${SRCS})
      message("Yes ${f}")
      phabos_add_srcs(${f})
    endforeach()
  endif()
endfunction()
